# Generated by Django 3.2.4 on 2021-06-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('desc', models.CharField(max_length=500)),
                ('price', models.FloatField(default=0.0)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2)),
                ('category', models.CharField(choices=[('SH', 'Shirt'), ('TS', 'T-Shirt'), ('TR', 'Trouser')], max_length=2)),
                ('img1', models.ImageField(default='', upload_to='ecomm/images')),
                ('img2', models.ImageField(default='', upload_to='ecomm/images')),
                ('img3', models.ImageField(default='', upload_to='ecomm/images')),
            ],
        ),
    ]
