# Generated by Django 3.2.4 on 2021-06-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_auto_20210609_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_cvv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='card_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
